const productsRoute = require('./products.route') 
const homeRoute = require('./home.route')
const searchRoute = require('./search.route')
const cartRoute = require('./cart.route')
const checkoutRoute = require('./checkout.route')
const userRoute = require('./user.route')
const chatRoute = require('./chat.route')

const categoryMiddleware = require('../../middlewares/client/category.middleware')
const cartIdMiddleware = require('../../middlewares/client/cart.middleware')
const userMiddleware = require('../../middlewares/client/user.middleware')
const settingGeneralMiddleware = require('../../middlewares/client/setting.middleware')
module.exports = (app) => { 
    app.use(categoryMiddleware.category)
    app.use(cartIdMiddleware.cartId)
    app.use(userMiddleware.infoUser)
    app.use(settingGeneralMiddleware.settingGeneral)
    app.use('/', homeRoute) 
    app.use('/products', productsRoute) 
    app.use('/search', searchRoute) 
    app.use('/cart', cartRoute) 
    app.use('/checkout', checkoutRoute) 
    app.use('/user', userRoute) 
    app.use('/chat', chatRoute) 
}